### ISSUE TITLE
Serial debug code

### ISSUE THREAD

**Issue by carlosperate** [Grrtzm/MicrobitV2-HHS#1]
Hi,

First of all thanks for sharing these Arduino libraries for the micro:bit, they look really useful!

I've noticed there some serial code in the library code, perhaps debugging code that can be removed?

https://github.com/Grrtzm/MicrobitV2-HHS/blob/4b01c02678decc95521da96a1a4d2cca7b1895df/src/Tone.cpp#L44-L49

https://github.com/Grrtzm/MicrobitV2-HHS/blob/4b01c02678decc95521da96a1a4d2cca7b1895df/src/Servo.cpp#L38

**Comment by Grrtzm** [comment]
Thanks! I Remove the Serial.* debugging commands.
